num_rounds: 25
num_clients: 5
fraction_fit: 1.0
fraction_evaluate: 1.0
num_clients_per_round_fit: 1
num_clients_per_round_eval: 1

save_path: "plots/results"
strategy: ContFedAvg


dataset:
  distribution: dirichlet
  plot_label_distribution: False
  num_classes_per_partition: 5 # used only for pathological distribution
  alpha: 0.5
  batch_size: 10


trainer:
  gamma: 0.2
  device: cpu
  num_epochs: 2
  lr: 0.1

# Comment the two sections below to make hydra generate the files again
# defaults:  
#   - _self_  
#   - override hydra/hydra_logging: disabled
#   - override hydra/job_logging: disabled

# hydra:
#   output_subdir: null
#   run:
#     dir: .