num_rounds: 3
num_clients: 3

dataset:
  distribution: linear
  plot_label_distribution: False
  alpha: 1
  batch_size: 32


trainer:
  num_epochs: 2
  lr: 0.01

# Comment the two sections below to make hydra generate the files again
# defaults:  
#   - _self_  
#   - override hydra/hydra_logging: disabled
#   - override hydra/job_logging: disabled

# hydra:
#   output_subdir: null
#   run:
#     dir: .